name: Pull Request Check
on:
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
env:
  GO_VERSION: "1.20"
jobs:
  unit-tests:
    name: 'Unit tests in ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 'Setup go ${{ env.GO_VERSION }}'
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: 'Check out project files'
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Run unit tests and generage HTML coverage report'
        run: |
          make unit-test-cov
  integration-tests:
    name: 'Integration tests in ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: 'Pull postgres 14.4 docker image so it is available for integeration test'
        run: |
          docker pull postgres:14.4
      - name: 'Run integration tests and generage HTML coverage report'
        run: |
          make integration-test-cov

  lint:
      name: 'Linting tests'
      runs-on: ubuntu-20.04
      steps:
        - name: 'Setup go ${{ env.GO_VERSION }}'
          uses: actions/setup-go@v4
          with:
            go-version: ${{ env.GO_VERSION }}
        - name: 'Check out project files'
          uses: actions/checkout@v3
          with:
            submodules: false
        - name: 'Run linting checks'
          run: |
            make test-lint
